version: "3.1"

volumes:
  db-data:
    driver: local

services:
  postgres:
    image: postgres:15.4-alpine
    container_name: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5436:5432"
    volumes:
      - db-data:/var/lib/postgresql/data