version: "3.1"

volumes:
  db-data-dev:
    driver: local

services:
  app:
    build:
      context: .
    container_name: tasklist-app
    env_file:
      - develop.env
    depends_on:
      - postgres-dev
    ports:
      - "8082:8080"

  postgres-dev:
    image: postgres:15.4-alpine
    container_name: postgres-dev
    env_file:
      - develop.env
    volumes:
      - db-data-dev:/var/lib/postgresql/data
