spring:
  devtools:
    add-properties: false
  config:
    import: optional:file:./develop.env[.properties]
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:liquibase/db.changelog.yaml
    enabled: true
    default-schema: ${POSTGRES_SCHEMA}
  sql:
    init:
      mode: never
      continue-on-error: false
  jpa:
    show-sql: true

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-expiration: ${JWT_ACCESS_EXPIRED}
    refresh-expiration: ${JWT_REFRESH_EXPIRED}

springdoc:
  override-with-generic-response: false

logging:
  config: classpath:logback-dev.xml

#logging:
#  level:
#    root: debug


